name: linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt -r playwright_part/requirements-pw.txt -r appium_part/requirements-appium.txt
    - name: linting PW-part with black
      run: 
        black --check playwright_part/
    - name: linting PW-part with isort
      run: 
        isort --check-only playwright_part/
    - name: linting PW-part with pylint
      run: 
        pylint playwright_part/
    - name: linting appium-part with black
      run:
        black --check appium_part/
    - name: linting appium-part with isort
      run:
        isort --check-only appium_part/
    - name: linting appium-part with pylint
      run:
        pylint appium_part/
